Cirify/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from scanner import views as scanner_views
from music import views as music_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # music
    url(r"^$", music_views.home, name="home"),
    url(r"^player", music_views.player, name="player"),
    # scanner
    url(r"^manager", scanner_views.scanner, name="manager"),
    url(r"^controller/", include('controller.urls'))
]

controller/urls.py
from django.conf.urls import url

from . import views

app_name = "controller"

urlpatterns = [
    url(r'^$', views.play, name='play'),
]

controller/models.py
from django.db import models

from music.models import Playlist

STATUSES = [
    ("Ready", "ready"),
    ("Playing", "playing"),
    ("Paused", "paused"),
    ("Stopped", "stopped"),
]


class Que(models.Model):
    name = models.CharField(max_length=100)
    active = models.BooleanField(default=False)
    status = models.CharField(
        choices=STATUSES, blank=True, default="ready", max_length=16
    )
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    # pygame = models.

    def __str__(self):
        return f"[{self.date.strftime('%Y-%m-%d %H:%M')}] {self.name}"


class Config(models.Model):
    device = models.CharField(max_length=25)
    storage_path = models.FilePathField()

    def __str__(self):
        return self.device

music/models.py
from django.db import models


class Playlist(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Album(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=250)
    playlist = models.ForeignKey(
        Playlist, related_name='albums', null=True, on_delete=models.SET_NULL, blank=True
    )

    def __str__(self):
        return self.location


class Song(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=250)
    album = models.ForeignKey(
        Album, related_name='songs', on_delete=models.CASCADE, blank=True
    )
    playlist = models.ForeignKey(
        Playlist, related_name='songs', null=True, on_delete=models.SET_NULL, blank=True
    )

    def __str__(self):
        return f"[{self.album}] {self.name}"

controller/views.py
from Cirify import tasks as t

from django.http import HttpResponseRedirect

from .models import Que
from music.models import Playlist


# todo: make it an API
def play(request):
    que_id = request.POST.get('que_id', False)
    que = Que.objects.get(id=que_id)
    # import pdb; pdb.set_trace()
    if True:
    # if not que.active and que.status == 'Ready':
        # activate que
        # todo: django fails here - needs to be handled in Celery
        from controller import pygame_wrapper as pw
        t.test_task.delay()
        # import pdb; pdb.set_trace()
        pygame = t.init.delay()
        que.active = True
        que.save(update_fields=["active"])
        song = que.playlist.songs.first().location
        # t.play.delay(song, pygame)
        que.status = 'Playing'
        que.save(update_fields=["status"])
        # fetch playlist and que songs
        # for song in que.playlist.songs.only('location').iterator():
        #     p.queue(song)
        # p.play()
    # todo: take que, fetch all the songs, init pygame, que the songs and play
    # todo: than change que to active and redirect to previous page
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

music/views.py
from django.shortcuts import render

from controller.models import Que


def home(request):
    return render(request, "music/home.html")


def player(request):
    que = Que.objects.last()
    context = {
        "que": que
    }
    return render(request, "music/player.html", context)

scanner/views.py
from django.shortcuts import render


def scanner(request):
    return render(request, "scanner/manager.html")

music/templates/music/home.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block title %}
    <h1>CIRIfy: home</h1>
{% endblock %}

{% block content %}
{% endblock %}

music/templates/music/player.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block title %}
    <h1>CIRIfy: music player</h1>
{% endblock %}

{% block content %}
    <h4>que:
        {% if que.active %}
            [x]
        {% else %}
            [ ]
        {% endif %}
        [{{ que.status  }}]
        [{{ que.date }}]
        {{ que.name }}
    </h4>
    <form action="{% url 'controller:play' %}" method="post" id="Play">
    {% csrf_token %}
        <button class="btn info" type="submit" form="Play" name="que_id" value="{{ que.id }}">
            play
        </button>
    </form>
{% endblock %}

scanner/templates/scanner/manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music manager</title>
</head>
<body>
<h1>music manager</h1>
</body>
</html>

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CIRIfy</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    {% block title %}
    {% endblock %}
    <p></p>

    <h3><a href="{% url 'home'%}" class="">> home</a></h3>
    <h3><a href="{% url 'manager'%}" class="">> manager</a></h3>
    <h3><a href="{% url 'player'%}" class="">> player</a></h3>

    {% block content %}
    {% endblock %}
</body>
</html>